### ISSUE TITLE
ontBean is_a type could be incorporated into type from individualsBean

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#425]
These two methods perform the same function so could be merged up into the ontBean.

Just need to be careful this doesn't unintentionally break anything.

**Comment by dosumis** [comment]
The only important difference is that classification/relationships on individuals are Type axioms, rather than Subclassof axioms (as on classes).  Processing, once you have the resulting class expressions, can be done identically.  The non-hacky way to distinguish classification (is_a) from relationships is to check whether the class expression is anonymous.  If it is, it is (in obo parlance) a relationship.

**Comment by Robbie1977** [comment]
this has been superseded by SOLR changes

**Comment by dosumis** [comment]
Yep.  The beans must die.  The sooner the better.
