### ISSUE TITLE
Centre FlyCircuit images on brightest slice

### ISSUE THREAD

**Issue by jefferis** [VirtualFlyBrain/VFB#45]
From June 2013

Marta and I wrote something to calculate the brightest slice for each stack in the flycircuit set in response to Douglas' suggestion. Spreadsheet and summary histogram attached.

Also, I guess @Nestor, Robbie and perhaps Bill, I noticed for the first time that the woolz data in the vfb browser has 326 slices, not 218 like the JFRC2 template. I presume that the stack has been inflated 50% in Z by adding interpolated slices, rather than by changing the Z spacing, and that strikes me as an odd choice. Is there a reason?

Data here: https://gist.github.com/jefferis/9411291

Note that this is the current list of [good_images](https://gist.github.com/jefferis/9411365), which excludes 3 images in that list (leaving 16129).

![brightestslicesflycircuit](https://f.cloud.github.com/assets/23763/2357200/80f34d0e-a5fa-11e3-9ee5-d96ea3493ef6.png)

**Comment by Robbie1977** [comment]
Just for clarification on this thread the woolz isn't technically inflated it's just the woolz server is calculating new 'virtual' planes rather than using the actual scan slices - it doesn't notice the fact we happen to be viewing in the same plane as the original was scanned. We could adjust the number of slices if needed but should be fine calculating relevant slice.

**Comment by Robbie1977** [comment]
Done on first 500 and works fine so will deploy in the rest when they have finished regenerating tomorrow.

example http://vfbdev.inf.ed.ac.uk/owl/VFB_00000007
