### ISSUE TITLE
Viewer image very dark

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#591]
The viewer in general just looks very dark, making it hard to see much structure in the nc82. Can it be made lighter?

http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100011,VFBd_00100010,VFBi_00005634,VFBi_00006011,VFBi_00003970,VFBi_00003972,VFBi_00010713

**Comment by Robbie1977** [comment]
alpha is now shown and auto scaling dependant on content

**Comment by mmc46** [comment]
I don't think this is good enough yet, so I am reopening to see if anything else could be done.
See the example in the png (example from features page). I changed the alpha, but this was the best I could do to see both the brain and the single neuron clearly. 
Not so much of a problem with the clones because the signal is quite strong.

![composite](https://cloud.githubusercontent.com/assets/1872083/8880947/3161faca-3234-11e5-9cfe-ebf73eb30a39.png)

**Comment by Robbie1977** [comment]
The issue is making it work for all content types, I could try giving an inverted option (the merging and construction is very different to make it work hence wasn't included in first draft).

Have a play on the old demo system and see if you can get what your looking from with canvas, I suspect this would involve pre-processing all the images to match levels:

Adjust position and test inverted:
http://vfbsandbox3.inf.ed.ac.uk/do/viewer2d.html?x=512&y=256&z=109&pit=0&yaw=0&rol=0&scl=1&dst=0.0&mod=zeta&qlt=80&cvt=png&alpha=255&inv=true&csy=318&csx=637&bg=bw&id=VFBt_00100000,VFBd_00100011,VFBd_00100010,VFBi_00005634,VFBi_00006011,VFBi_00003970,VFBi_00003972,VFBi_00010713#tabDisp

Test different blending mode using parameters from above:
http://vfbsandbox3.inf.ed.ac.uk/do/blendDemo.html?x=512&y=256&z=109&pit=0&yaw=0&rol=0&scl=1&dst=0.0&mod=zeta&qlt=80&cvt=png&alpha=255&inv=true&csy=318&csx=637&bg=bw&id=VFBt_00100000,VFBd_00100011,VFBd_00100010,VFBi_00005634,VFBi_00006011,VFBi_00003970,VFBi_00003972,VFBi_00010713#tabDisp

**Comment by Robbie1977** [comment]
Should be better now as was using grey - if not reopen
