### ISSUE TITLE
opening non-Janelia stacks

### ISSUE THREAD

**Issue by cahirokane** [VirtualFlyBrain/VFB#704]
When the Ito half-brain opens, the slider however is not very responsive - it often springs back, maybe because it can't swallow the overhead of moving through all the slices? Also, it's black on opening - I guess because it opens at slice 1, unlike the Janelia brain which opens (more sensibly) in the middle? The slider behaviour seems to apply also to other stacks.

Also, once a new stack is opened, the top right corner still says "Janelia Adult Brain", regardless of the stack that's opened. I'm opening in new tabs, in Safari.

It's obviously not as high a priority as getting the whole site working well with the default Janelia stack, and if it will work better in VFB2, it may not be worth fixing it at all in 1.5 - but I thought I'd mention it.

**Comment by Robbie1977** [comment]
Thanks for raising the issue - please do with anything you notice no matter how slight.

This is an issue with the system not loading the correct metadata file for the chosen template since we changed from using cookies last week.

It's already been raised in ticket #701 - now the search and flybase DB updates are fixed it's my next job so should be back to normal in the next few days.
