### ISSUE TITLE
want to search for GMR  71G01

### ISSUE THREAD

**Issue by jefferis** [VirtualFlyBrain/VFB#722]
1. GMR stacks are only searchable by typing 

```
GMR_71G01
```

whereas many people would just start typing 71G01 and expect to see something.

2. that particular line is available for downloaded but not indexed on the site. Any idea why?

Support info:
http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100011,VFBi_00020600,VFBd_00100031
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36 Size:[1352,977]
!M57-0.1!M4!6Z!e8e1!M1511,255,108!e1e!B Template!11!j1!F311!4v!7!P8!9e!L043982!12!I320600!4N!6GMR_71G02_AE_01_03-fA01b!13!j1!F331!4e!L0340042!G!H2!2S!20!2i!6!H2!F5!G!D8 Template!G!P3!0

**Comment by Robbie1977** [comment]
See #715 but really SOLR should return the partial match but isn't at the moment.

@dosumis has this changed on the OLS test server?

**Comment by dosumis** [comment]
May be some issue with how SOLR tokenisation deals with '_'. Meeting with
@simonjupp today. Will discuss.

**Comment by simonjupp** [comment]
Possible solution - tokenise on '_' .  Might want to consider other special characters coming in from gene and transgene names, e.g. { [ }

**Comment by Robbie1977** [comment]
@simonjupp is this something you plans to do in main repo?

**Comment by dosumis** [comment]
Robbie: Why is the tuning being pushed into the queries?  Can't we
configure our own query endpoint as part of setup - adapting Simon's
default setting?

**Comment by Robbie1977** [comment]
I believe simon gave up on trying to user anything put the default endpoints as it caused too many other issues so I don't think we should go down that route.
We can certainly add a custom item as simon has done to resolve this (label_autosuggest_e, label_autosuggest_ws, etc) but best to keep as close as possible to the OLS master as possible. Hence is simon intends to implement special character tokenisation then great, otherwise I'll have to figure out how to implement in our own branch.

An example of our current 'tuned' autosuggest query (for 'AMMC'):
 
http://vfbdev.inf.ed.ac.uk/search/select?hl=true&fl=short_form,label,synonym,id,type,has_narrow_synonym_annotation,has_broad_synonym_annotation&start=0&fq=ontology_name:(fbbt)&fq=is_obsolete:false&fq=shortform_autosuggest:VFB_*%20OR%20shortform_autosuggest:FBbt_*&rows=100&hl.simple.pre=%3Cb%3E&bq=is_defining_ontology:true^100.0%20label_s:%22AMMC%22^2%20synonym_s:%22AMMC%22%20in_subset_annotation:BRAINNAME^3%20short_form:FBbt_00003982^2&q=AMMC&defType=edismax&hl.simple.post:%3C/b%3E&qf=label%20synonym%20label_autosuggest_ws%20label_autosuggest_e%20label_autosuggest%20synonym_autosuggest_ws%20synonym_autosuggest_e%20synonym_autosuggest%20shortform_autosuggest%20has_narrow_synonym_annotation%20has_broad_synonym_annotation&hl.fl=label_autosuggest&hl.fl=label&hl.fl=synonym_autosuggest&hl.fl=synonym&wt=json&indent=true

**Comment by dosumis** [comment]
Isn't there a performance cost to pushing the tuning into the query?

**Comment by Robbie1977** [comment]
This is how OLS is doing it (unless simon has changed it recently), the only real addition is a tweak to return AMMC over saddle when searching AMMC as requested by Marta as both are BRAINNAME terms with AMMC as synonym.

**Comment by Robbie1977** [comment]
Improved autocomplete implemented
